version: "3"
services:
  
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    container_name: kodezi-ui
    networks:
      - kodezi-stack-net
    depends_on:
      - api
    stdin_open: true
    tty: true

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 3080:3080
    container_name: kodezi-api
    networks:
      - kodezi-stack-net
    depends_on:
      - db

  db:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongo-db
    networks:
      - kodezi-stack-net
    volumes:
      - mongo-data:/data/db

networks:
  kodezi-stack-net:
    driver: bridge

volumes:
  exclude:
  mongo-data:
    driver: local